# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Systematic Resampling
NULL

systematic_sample_cpp <- function(n_particles, norm_weights) {
    .Call('_EpiSky_systematic_sample_cpp', PACKAGE = 'EpiSky', n_particles, norm_weights)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_EpiSky_RcppExport_registerCCallable', PACKAGE = 'EpiSky')
})
